const ACTIVATE_CELL = 'ACTIVATE_CELL';
const ADD_CELL_TO_SELECTIONS = 'ADD_CELL_TO_SELECTIONS';
const ADD_COLUMN_WIDTH = 'ADD_COLUMN_WIDTH';
const ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS = 'ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS';
const ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS = 'ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS';
const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';
const CLOSE_COLUMN_TYPE_MODAL = 'CLOSE_COLUMN_TYPE_MODAL';
const COPY_VALUES = 'COPY_VALUES';
const CREATE_COLUMNS = 'CREATE_COLUMNS';
const CREATE_ROWS = 'CREATE_ROWS';
const DELETE_ROWS = 'DELETE_ROWS';
const DELETE_COLUMN = 'DELETE_COLUMN';
const DELETE_FILTER = 'DELETE_FILTER';
const DELETE_VALUES = 'DELETE_VALUES';
const EXCLUDE_ROWS = 'EXCLUDE_ROWS';
const FILTER_COLUMN = 'FILTER_COLUMN';
const FILTER_EXCLUDE_ROWS = 'FILTER_EXCLUDE_ROWS';
const FILTER_SELECT_ROWS = 'FILTER_SELECT_ROWS';
const HIGHLIGHT_FILTERED_ROWS = 'HIGHLIGHT_FILTERED_ROWS';
const MODIFY_CURRENT_SELECTION_CELL_RANGE = 'MODIFY_CURRENT_SELECTION_CELL_RANGE';
const MODIFY_CURRENT_SELECTION_ROW_RANGE = 'MODIFY_CURRENT_SELECTION_ROW_RANGE';
const OPEN_ANALYSIS_WINDOW = 'OPEN_ANALYSIS_WINDOW';
const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
const PASTE_VALUES = 'PASTE_VALUES';
const PERFORM_ANALYSIS = 'PERFORM_ANALYSIS';
const PERFORM_DISTRIBUTION_ANALYSIS = 'PERFORM_DISTRIBUTION_ANALYSIS';
const REDO = 'REDO';
const REMOVE_FILTERED_ROWS = 'REMOVE_FILTERED_ROWS';
const REMOVE_HIGHLIGHTED_FILTERED_ROWS = 'REMOVE_HIGHLIGHTED_FILTERED_ROWS';
const REMOVE_SELECTED_CELLS = 'REMOVE_SELECTED_CELLS';
const REMOVE_SIDEBAR_FILTER = 'REMOVE_SIDEBAR_FILTER';
const RESIZE_COLUMN = 'RESIZE_COLUMN';
const SAVE_VALUES_TO_COLUMN = 'SAVE_VALUES_TO_COLUMN';
const SAVE_FILTER = 'SAVE_FILTER';
const SELECT_CELL = 'SELECT_CELL';
const SELECT_CELLS_BY_IDS = 'SELECT_CELLS_BY_IDS';
const SELECT_ALL_CELLS = 'SELECT_ALL_CELLS';
const SELECT_BLOCK_OF_CELLS = 'SELECT_BLOCK_OF_CELLS';
const SELECT_ROW = 'SELECT_ROW';
const SELECT_COLUMN = 'SELECT_COLUMN';
const SET_FILTERS = 'SET_FILTERS';
const SET_SELECTED_COLUMN = 'SET_SELECTED_COLUMN';
const SET_GROUPED_COLUMNS = 'SET_GROUPED_COLUMNS';
const SET_TABLE_NAME = 'SET_TABLE_NAME';
const SORT_COLUMN = 'SORT_COLUMN';
const TOGGLE_ANALYSIS_MODAL = 'TOGGLE_ANALYSIS_MODAL';
const TOGGLE_BAR_CHART_MODAL = 'TOGGLE_BAR_CHART_MODAL';
const TOGGLE_COLUMN_TYPE_MODAL = 'TOGGLE_COLUMN_TYPE_MODAL';
const TOGGLE_LAYOUT = 'TOGGLE_LAYOUT';
const TOGGLE_FILTER_MODAL = 'TOGGLE_FILTER_MODAL';
const TOGGLE_DISTRIBUTION_MODAL = 'TOGGLE_DISTRIBUTION_MODAL';
const TRANSLATE_SELECTED_CELL = 'TRANSLATE_SELECTED_CELL';
const UPDATE_CELL = 'UPDATE_CELL';
const UPDATE_COLUMN = 'UPDATE_COLUMN';
const UNEXCLUDE_ROWS = 'UNEXCLUDE_ROWS';
const UNDO = 'UNDO';

const ORDINAL = 'Ordinal';
const CONTINUOUS = 'Continuous';
const NOMINAL = 'Nominal';
const NUMBER = 'Number';
const STRING = 'String';
const FORMULA = 'Formula';
const BIVARIATE = 'Bivariate';
const LOGISTIC = 'Logistic';
const ONEWAY = 'Oneway';
const CONTINGENCY = 'Contingency';

export {
	ACTIVATE_CELL,
	ADD_CELL_TO_SELECTIONS,
	ADD_COLUMN_WIDTH,
	ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS,
	CLOSE_CONTEXT_MENU,
	CLOSE_COLUMN_TYPE_MODAL,
	COPY_VALUES,
	CREATE_COLUMNS,
	CREATE_ROWS,
	DELETE_COLUMN,
	DELETE_FILTER,
	DELETE_ROWS,
	DELETE_VALUES,
	EXCLUDE_ROWS,
	FILTER_COLUMN,
	FILTER_EXCLUDE_ROWS,
	FILTER_SELECT_ROWS,
	HIGHLIGHT_FILTERED_ROWS,
	MODIFY_CURRENT_SELECTION_CELL_RANGE,
	MODIFY_CURRENT_SELECTION_ROW_RANGE,
	OPEN_ANALYSIS_WINDOW,
	OPEN_CONTEXT_MENU,
	PASTE_VALUES,
	PERFORM_ANALYSIS,
	PERFORM_DISTRIBUTION_ANALYSIS,
	REDO,
	REMOVE_FILTERED_ROWS,
	REMOVE_HIGHLIGHTED_FILTERED_ROWS,
	REMOVE_SELECTED_CELLS,
	REMOVE_SIDEBAR_FILTER,
	RESIZE_COLUMN,
	SAVE_FILTER,
	SAVE_VALUES_TO_COLUMN,
	SELECT_CELL,
	SELECT_ALL_CELLS,
	SELECT_BLOCK_OF_CELLS,
	SELECT_ROW,
	SELECT_CELLS_BY_IDS,
	SELECT_COLUMN,
	SET_FILTERS,
	SET_GROUPED_COLUMNS,
	SET_SELECTED_COLUMN,
	SET_TABLE_NAME,
	SORT_COLUMN,
	TOGGLE_LAYOUT,
	TOGGLE_BAR_CHART_MODAL,
	TOGGLE_ANALYSIS_MODAL,
	TOGGLE_DISTRIBUTION_MODAL,
	TOGGLE_FILTER_MODAL,
	TOGGLE_COLUMN_TYPE_MODAL,
	TRANSLATE_SELECTED_CELL,
	UPDATE_CELL,
	UPDATE_COLUMN,
	UNEXCLUDE_ROWS,
	UNDO,
	ORDINAL,
	CONTINUOUS,
	NOMINAL,
	BIVARIATE,
	LOGISTIC,
	ONEWAY,
	CONTINGENCY,
	NUMBER,
	STRING,
	FORMULA,
};
