const ACTIVATE_CELL = 'ACTIVATE_CELL';
const ADD_CELL_TO_SELECTIONS = 'ADD_CELL_TO_SELECTIONS';
const ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS = 'ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS';
const ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS = 'ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS';
const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';
const COPY_VALUES = 'COPY_VALUES';
const CREATE_COLUMNS = 'CREATE_COLUMNS';
const CREATE_ROWS = 'CREATE_ROWS';
const DELETE_ROW = 'DELETE_ROW';
const DELETE_COLUMN = 'DELETE_COLUMN';
const DELETE_VALUES = 'DELETE_VALUES';
const FILTER_COLUMN = 'FILTER_COLUMN';
const MODIFY_CURRENT_SELECTION_CELL_RANGE = 'MODIFY_CURRENT_SELECTION_CELL_RANGE';
const MODIFY_CURRENT_SELECTION_ROW_RANGE = 'MODIFY_CURRENT_SELECTION_ROW_RANGE';
const OPEN_ANALYSIS_WINDOW = 'OPEN_ANALYSIS_WINDOW';
const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
const PASTE_VALUES = 'PASTE_VALUES';
const PERFORM_ANALYSIS = 'PERFORM_ANALYSIS';
const PERFORM_DISTRIBUTION_ANALYSIS = 'PERFORM_DISTRIBUTION_ANALYSIS';
const REMOVE_SELECTED_CELLS = 'REMOVE_SELECTED_CELLS';
const SELECT_CELL = 'SELECT_CELL';
const SELECT_CELLS = 'SELECT_CELLS';
const SELECT_ALL_CELLS = 'SELECT_ALL_CELLS';
const SELECT_ROW = 'SELECT_ROW';
const SELECT_COLUMN = 'SELECT_COLUMN';
const SET_SELECTED_COLUMN = 'SET_SELECTED_COLUMN';
const SET_GROUPED_COLUMNS = 'SET_GROUPED_COLUMNS';
const SORT_COLUMN = 'SORT_COLUMN';
const TOGGLE_LAYOUT = 'TOGGLE_LAYOUT';
const TOGGLE_COLUMN_TYPE_MODAL = 'TOGGLE_COLUMN_TYPE_MODAL';
const TOGGLE_FILTER_MODAL = 'TOGGLE_FILTER_MODAL';
const TOGGLE_ANALYSIS_MODAL = 'TOGGLE_ANALYSIS_MODAL';
const TOGGLE_DISTRIBUTION_MODAL = 'TOGGLE_DISTRIBUTION_MODAL';
const TRANSLATE_SELECTED_CELL = 'TRANSLATE_SELECTED_CELL';
const UPDATE_CELL = 'UPDATE_CELL';
const UPDATE_COLUMN = 'UPDATE_COLUMN';

export {
	ACTIVATE_CELL,
	ADD_CELL_TO_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS,
	CLOSE_CONTEXT_MENU,
	COPY_VALUES,
	CREATE_COLUMNS,
	CREATE_ROWS,
	DELETE_VALUES,
	DELETE_ROW,
	DELETE_COLUMN,
	FILTER_COLUMN,
	MODIFY_CURRENT_SELECTION_CELL_RANGE,
	MODIFY_CURRENT_SELECTION_ROW_RANGE,
	OPEN_ANALYSIS_WINDOW,
	OPEN_CONTEXT_MENU,
	PASTE_VALUES,
	PERFORM_ANALYSIS,
	PERFORM_DISTRIBUTION_ANALYSIS,
	REMOVE_SELECTED_CELLS,
	SELECT_CELL,
	SELECT_CELLS,
	SELECT_ALL_CELLS,
	SELECT_ROW,
	SELECT_COLUMN,
	SET_GROUPED_COLUMNS,
	SET_SELECTED_COLUMN,
	SORT_COLUMN,
	TOGGLE_LAYOUT,
	TOGGLE_ANALYSIS_MODAL,
	TOGGLE_DISTRIBUTION_MODAL,
	TOGGLE_FILTER_MODAL,
	TOGGLE_COLUMN_TYPE_MODAL,
	TRANSLATE_SELECTED_CELL,
	UPDATE_CELL,
	UPDATE_COLUMN,
};
