const ACTIVATE_CELL = 'ACTIVATE_CELL';
const ADD_CELL_TO_SELECTIONS = 'ADD_CELL_TO_SELECTIONS';
const ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS = 'ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS';
const CREATE_COLUMNS = 'CREATE_COLUMNS';
const CREATE_ROWS = 'CREATE_ROWS';
const DELETE_VALUES = 'DELETE_VALUES'
const MODIFY_CURRENT_SELECTION_CELL_RANGE = 'MODIFY_CURRENT_SELECTION_CELL_RANGE';
const SELECT_CELL = 'SELECT_CELL';
const SET_ROW_POSITION = 'SET_ROW_POSITION';
const TRANSLATE_SELECTED_CELL = 'TRANSLATE_SELECTED_CELL';
const UPDATE_CELL = 'UPDATE_CELL';

export {
  ACTIVATE_CELL,
  ADD_CELL_TO_SELECTIONS,
  ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS,
  CREATE_COLUMNS,
  CREATE_ROWS,
  DELETE_VALUES,
  MODIFY_CURRENT_SELECTION_CELL_RANGE,
  SELECT_CELL,
  SET_ROW_POSITION,
  TRANSLATE_SELECTED_CELL,
  UPDATE_CELL
}