/*global chrome*/
import EventBus from './eventbus';
import {
	ACTIVATE_CELL,
	ADD_CELL_TO_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS,
	CLOSE_CONTEXT_MENU,
	COPY_VALUES,
	CREATE_COLUMNS,
	CREATE_ROWS,
	DELETE_COLUMN,
	DELETE_FILTER,
	DELETE_ROWS,
	DELETE_VALUES,
	EXCLUDE_ROWS,
	FILTER_COLUMN,
	FILTER_COLUMN_BY_STRING,
	MODIFY_CURRENT_SELECTION_CELL_RANGE,
	MODIFY_CURRENT_SELECTION_ROW_RANGE,
	OPEN_ANALYSIS_WINDOW,
	OPEN_CONTEXT_MENU,
	PASTE_VALUES,
	PERFORM_ANALYSIS,
	PERFORM_DISTRIBUTION_ANALYSIS,
	REMOVE_SELECTED_CELLS,
	SELECT_CELL,
	SELECT_CELLS,
	SELECT_ALL_CELLS,
	SELECT_ROW,
	SELECT_COLUMN,
	SET_FILTERS,
	SET_GROUPED_COLUMNS,
	SET_SELECTED_COLUMN,
	SORT_COLUMN,
	TOGGLE_LAYOUT,
	TOGGLE_BAR_CHART_MODAL,
	TOGGLE_ANALYSIS_MODAL,
	TOGGLE_DISTRIBUTION_MODAL,
	TOGGLE_FILTER_MODAL,
	TOGGLE_COLUMN_TYPE_MODAL,
	TRANSLATE_SELECTED_CELL,
	UPDATE_CELL,
	UPDATE_COLUMN,
	UNEXCLUDE_ROWS,
	SAVE_VERSION
} from './constants';
const ALL_UNDERSCORES = /_/g;

function handlingTableEvent({type, ...event}) {
	const eventName = type.toLowerCase().replace(ALL_UNDERSCORES, '-');
	chrome.runtime.sendMessage({
		type: 'aggregate-event',
	  aggregate: 'dataTable', eventName, event
	});
}
const eventBus = new EventBus('data-table-events', console.debug);
[
	ACTIVATE_CELL,
	ADD_CELL_TO_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_CELL_SELECTIONS,
	ADD_CURRENT_SELECTION_TO_ROW_SELECTIONS,
	CLOSE_CONTEXT_MENU,
	COPY_VALUES,
	CREATE_COLUMNS,
	CREATE_ROWS,
	DELETE_COLUMN,
	DELETE_FILTER,
	DELETE_ROWS,
	DELETE_VALUES,
	EXCLUDE_ROWS,
	FILTER_COLUMN,
	FILTER_COLUMN_BY_STRING,
	MODIFY_CURRENT_SELECTION_CELL_RANGE,
	MODIFY_CURRENT_SELECTION_ROW_RANGE,
	OPEN_ANALYSIS_WINDOW,
	OPEN_CONTEXT_MENU,
	PASTE_VALUES,
	PERFORM_ANALYSIS,
	PERFORM_DISTRIBUTION_ANALYSIS,
	REMOVE_SELECTED_CELLS,
	SELECT_CELL,
	SELECT_CELLS,
	SELECT_ALL_CELLS,
	SELECT_ROW,
	SELECT_COLUMN,
	SET_FILTERS,
	SET_GROUPED_COLUMNS,
	SET_SELECTED_COLUMN,
	SORT_COLUMN,
	TOGGLE_LAYOUT,
	TOGGLE_BAR_CHART_MODAL,
	TOGGLE_ANALYSIS_MODAL,
	TOGGLE_DISTRIBUTION_MODAL,
	TOGGLE_FILTER_MODAL,
	TOGGLE_COLUMN_TYPE_MODAL,
	TRANSLATE_SELECTED_CELL,
	UPDATE_CELL,
	UPDATE_COLUMN,
	UNEXCLUDE_ROWS,
	SAVE_VERSION
].forEach((event) => {
	eventBus.subscribe(event, handlingTableEvent);
});

export default eventBus;
